#!/bin/sh
ncverilog -q -R +nc64bit +name+snap_mkDM_Interface +nclibdirname+INCA_libs_mkDM_Interface $*
status=$?
if [ "$status" != "0" ]; then
    echo "ERROR: cannot simulate design" >&2
    exit $status
fi
